apiVersion: v1
kind: Service
metadata:
  name: ms-projects
spec:
  clusterIP: 172.30.220.36
  clusterIPs:
  - 172.30.220.36
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ms-projects
  sessionAffinity: None
  type: ClusterIP