apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-process
  template:
    metadata:
      labels:
        app: ms-process
    spec:
      containers:
        - name: server
          envFrom:
            - secretRef:
                name: process-secret
          image: jmartinezblanco/meta-ms-process
