apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    spec:
      containers:
      - image: jmartinezblanco/spa-kustomize
        imagePullPolicy: Always
        name: meta-spa
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom: 
          - secretRef:
              name: spa-secret
        resources: {}