apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-organization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-organization
  template:
    metadata:
      labels:
        app: ms-organization
    spec:
      containers:
        - name: server
          envFrom:
            - secretRef:
                name: organization-secret
          envFrom:
            - secretRef:
                name: db-secret
          image: jmartinezblanco/meta-ms-organization
