apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-surveys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-surveys
  template:
    metadata:
      labels:
        app: ms-surveys
    spec:
      containers:
        - name: ms-surveys
          envFrom:
            - secretRef:
                name: surveys-secret
          image: jmartinezblanco/meta-ms-surveys
